webapp/config/routes.rb
 Rails.application.routes.draw do


    root 'pages#index'
    get 'first' => 'pages#first'
    get 'press' => 'pages#press'
    get 'outreach' => 'pages#outreach'
    get 'press' => 'pages#viewpress'
    get 'press/new' => 'pages#newpost'
    get 'calendar' => 'pages#calendar'
    get '/post/:title' => 'pages#show'
    get 'with/drew' => 'pages#drew'
    get 'awards' => 'pages#awards'
    get 'links' => 'pages#links'

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy'

    get 'admin' => "admin#home"
    get 'admin/outreach' => 'admin#manage_outreach'
    get 'admin/outreach/new' => 'admin#new_outreach'
    get 'admin/post/:id/edit' => 'admin#edit_post'
    get 'admin/post/:id/delete' => 'admin#delete_post'
    patch 'admin/post/:id' => 'admin#update_post'

    get 'admin/awards' => 'admin#manage_awards'
    get 'admin/awards/new' => 'admin#new_award'
    post 'admin/awards' => 'admin#create_award'
    get 'admin/awards/:id/edit' => 'admin#edit_award'
    patch 'admin/awards/:id' => 'admin#update_award'
    get 'admin/awards/:id/delete' => 'admin#delete_award'

    post '/outreach' => 'admin#create_outreach'
    get 'admin/press' => 'admin#manage_press'
    get 'admin/press/new' => 'admin#new_press'
    post '/press' => 'admin#create_press'
    get 'admin/members' => 'admin#manage_members'
    get 'admin/widgets' => 'admin#manage_widgets'
    get 'admin/widgets/:id/edit' => 'admin#edit_widget'
    patch 'admin/widgets/:id' => 'admin#update_widget'

    get 'admin/users' => 'admin#manage_users'
    get 'admin/users/new' => 'admin#new_user'
    post 'admin/users' => 'admin#create_user'
    get 'admin/users/:id/edit' => 'admin#edit_user'
    patch 'admin/users/:id' => 'admin#update_user'
    get 'admin/users/:id/delete' => 'admin#delete_user'

    get 'admin/sponsors' => 'admin#manage_sponsors'
    get 'admin/sponsors/delete' => 'admin#delete_sponsor'
    post 'admin/sponsors/new' => 'admin#new_sponsor'

    resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

webapp/app/views/layouts/_admin_header.html.erb
<header class="admin-header">
  <div class="admin">
    <p class="name"><%= current_user.name %></p>
    <p class="role">
      <% if current_user.role == 1 %>
      <%= "Viewer" %>
      <% elsif current_user.role == 2 %>
      <%= "Publisher" %>
      <% elsif current_user.role == 3 %>
      <%= "Admin" %>
      <% elsif current_user.role == 4 %>
      <%= "Superadmin" %>
      <% elsif current_user.role > 4 %>
      <%= "God" %>
      <% end %>
    </p>
  </div>
  <nav>
    <div><%= link_to 'Dashboard', :controller => :admin, :action => :home %>
</div>
    <div><%= link_to 'Outreach', :controller => :admin, :action => :manage_outreach %>
</div>
    <div><%= link_to 'Press', :controller => :admin, :action => :manage_press %>
</div>
    <div><%= link_to 'Widgets', :controller => :admin, :action => :manage_widgets %>
</div>
<div><%= link_to 'Awards', :controller => :admin, :action => :manage_awards %>
</div>
    <div><%= link_to 'Sponsors', :controller => :admin, :action => :manage_sponsors %>
    <!-- <div><%= link_to 'Members', :controller => :admin, :action => :manage_members %> -->
</div>
    <div><%= link_to 'Users', :controller => :admin, :action => :manage_users %>
</div>
  </nav>
  <%= link_to 'Back to Site', '/', :class => "back-to-site" %>
  <%= link_to 'Logout', '/logout', :class => "logout" %>
</header>

webapp/app/views/layouts/_footer.html.erb
<footer>
  <div>
    <div>
      <h3>NAVIGATION</h3>
      <%= link_to 'Home', root_path %>
      <%= link_to 'First', first_path %>
      <%= link_to 'Press', press_path %>
      <%= link_to 'Outreach', outreach_path %>
    </div>
    <div>
      <h3>RESOURCES</h3>
      <%= link_to 'Calendar', calendar_path %>
      <%= link_to 'Awards', awards_path %>
      <%= link_to 'Team Links', links_path %>
    </div>
    <p>
      &copy; HBRLive!  Designed and made by HBR Web Development.
    </p>
  </div>
</footer>

webapp/app/views/layouts/_header.html.erb
<header class="mobile-header">
  <div class="nav-icon" id="nav-icon"><i class="fa fa-bars fa-lg" aria-hidden="true"></i></div>
  <div class="mobile-nav-content">
    <nav>
      <div>
        <%= link_to first_path do %> FIRST<% end %>
        <div class="dropdown">
        </div>
      </div>
      <div>
        <%= link_to press_path do %> PRESS <i class="fa fa-chevron-down dropdown-chevron" aria-hidden="true" id="dropdown-chevron"></i><% end %>
        <div class="dropdown">
          <%= link_to 'Panda Press', press_path %>
          <%= link_to 'Outreach', outreach_path %>
          <!-- <a href="#">Leagues</a> -->
        </div>
      </div>
      <div>
        <%= link_to root_path do %> INFO <i class="fa fa-chevron-down dropdown-chevron" aria-hidden="true" id="dropdown-chevron"></i><% end %>
        <div class="dropdown">
          <%= link_to 'Calendar', calendar_path %>
          <%= link_to 'Awards', awards_path %>
          <!-- <a href="#">Leagues</a> -->
        </div>
      </div>
    </nav>
  </div>
</header>
<header class="header-main">
    <div>
        <%= link_to root_path do %>Team <span>1747</span><% end %>
        <nav>
            <div>
              <%= link_to root_path do %> INFO <i class="fa fa-chevron-down dropdown-chevron" aria-hidden="true" id="dropdown-chevron"></i><% end %>
              <div class="dropdown">
                <%= link_to 'Calendar', calendar_path %>
                <%= link_to "Awards", awards_path %>
                <!-- <a href="#">Leagues</a> -->
              </div>
            </div>
            <div>
              <%= link_to press_path do %> PRESS <i class="fa fa-chevron-down dropdown-chevron" aria-hidden="true" id="dropdown-chevron"></i><% end %>
              <div class="dropdown">
                <%= link_to 'Panda Press', press_path %>
                <%= link_to 'Outreach', outreach_path %>
                <!-- <a href="#">Leagues</a> -->
              </div>
            </div>
            <div>
              <%= link_to first_path do %> FIRST<% end %>
              <!-- <div class="dropdown">
                <a href="#">Games</a>
                <a href="#">Leagues</a>
              </div> -->
            </div>
        </nav>
    </div>
</header>

webapp/app/views/layouts/_post_image.html.erb
<!-- # <% if @post %>
#   <% if @post.image %>
#   <%= image_tag("/post_images/#{@post.id}/post.png")%>
#   <% else %>
#   <%= image_tag("/post_images/#{@post.id}/post.png")%>
#   <% end %>
# <% end %> -->

webapp/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Harrison Boiler Robotics</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://use.fontawesome.com/ab131db148.js' %>
  </head>

  <body>
    <%= render "layouts/admin_header" %>
    <div class="admin-content">
    <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Harrison Boiler Robotics</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <meta name=”viewport” content=”width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;” />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://use.fontawesome.com/ab131db148.js' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

webapp/app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Harrison Boiler Robotics</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://use.fontawesome.com/ab131db148.js' %>
  </head>

  <body>
    <%= render "layouts/admin_header" %>
    <div class="admin-content">
    <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>